---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: heading
  label: Content
- type: directory
  path: content/smallProjects
  label: Small Projects
  create: documents
  match: "**/*"
  new_doc_ext: md
  templates:
  - small-project
- type: directory
  path: content/projects
  label: Projects
  create: documents
  match: "**/*"
  new_doc_ext: md
  templates:
  - project
- type: directory
  path: content/pages
  label: Pages
  create: documents
  match: "**/*"
  new_doc_ext: md
  templates:
  - page
- type: directory
  path: content/blogPosts
  label: Blog Posts
  create: documents
  match: "**/*"
  new_doc_ext: md
  templates:
  - blog-post
- type: heading
  label: Index Config
- type: document
  path: content/mainData/index.md
  label: Index
- type: document
  path: content/mainData/projectOrder.md
  label: Project Order
- type: document
  path: config.json
  label: Site Metadata
upload_dir: content/images
public_path: "../images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: public
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run forestry-preview
